---

- name: install AD-Domain-Services 
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes

- name: setup AD controller
  win_domain:
   dns_domain_name: "{{ ad_domain_name }}"
   safe_mode_password: "{{ ad_safe_mode_password }}"
   domain_admin_user: "{{ ad_admin_user }}"
   domain_admin_password: "{{ ad_admin_password }}" 
  register: ad_controller 

- name: reboot | Rebooting Server
  win_reboot:
  when: ad_controller['reboot_required'] 
      

- name: Listout domain DCs
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list
