---


- name: install openssh on windows
  win_chocolatey:
    name: "{{ package_name}}"
    params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: start ssh service
  win_service:
       name: "{{ service_name }}"
       state: started
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Firewall rule to allow ssh on TCP port 22
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{  local_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
